export const ADD_CUSTOMER = "ADD_PRODUCT";
export const RETRIEVE_CUSTOMERS = "RETRIEVE_CUSTOMERS";
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";
export const DELETE_CUSTOMER = "DELETE_CUSTOMER";